name: autotest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        run: sh autotest.sh
