name: autotest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        run: . autotest.sh
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: validate-result
          path: validate-results.tar.gz
