name: autotest

on:

  push:
    branches: [ main develop ]

  pull_request:
    branches: [ main develop ]
    
  workflow_dispatch:

jobs:

  autotest:

    runs-on: debian:11

    steps:
    
      - uses: actions/checkout@v2

      - name: validate
        run: sh autotest.sh
